### your site title here

title: What This MUSIC!
description: A description about What This MUSIC!
baseurl:  # name of the repository
email: your@email.com
url: https://whatthismusic.com


highlighter: rouge
markdown: kramdown
### exclude the instructions / write-up in the README.md


# Tracker
#analytics: UA-83979019-1

# Comments
#disqus-shortname: webjeda-demo

# Date format
date_format: "%b %-d, %Y"

#optimization
#compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

# Pagination
paginate: 5
paginate_path: "/page/:num"

# Tags config for jekyll-tagging
tag_page_layout: tag_page
tag_page_dir: tag

sass:
 style: compressed

exclude:
- README.md

plugins:
  - jekyll-seo-tag
  - jekyll-org
  - jekyll-feed
  - jekyll-paginate
  - jekyll/tagging